//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NetChess.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_NETCHETYPE                  129
#define IDD_DIALOG_OPTIONS              131
#define IDB_BITMAP_BASE                 132
#define IDB_BITMAP_ROOK_WHITE           133
#define IDB_BITMAP_BISHOP_WHITE         134
#define IDB_BITMAP_KING_BLACK           135
#define IDB_BITMAP_KING_WHITE           136
#define IDB_BITMAP_KNIGHT_BLACK         137
#define IDB_BITMAP_KNIGHT_WHITE         138
#define IDB_BITMAP_PAWN_BLACK           139
#define IDB_BITMAP_PAWN_WHITE           140
#define IDB_BITMAP_QUEEN_BLACK          141
#define IDB_BITMAP_QUEEN_WHITE          142
#define IDB_BITMAP_ROOK_BLACK           143
#define IDB_BITMAP_BISHOP_BLACK         144
#define IDD_DIALOG_SERVER_INFO          145
#define IDD_DIALOG_MESSAGE              146
#define IDD_DIALOG_HISTORY              147
#define IDD_DIALOG_PICK_PIECE           148
#define IDI_ICON_MAINFRAME_OPPOSITE     149
#define IDR_SHELL_MENU                  150
#define IDD_DIALOG_PROPERTIES           177
#define IDD_DIALOG_GAME_TYPE            178
#define IDB_DICE                        180
#define IDB_DICE1                       181
#define IDB_DICE2                       182
#define IDB_DICE3                       183
#define IDB_DICE4                       184
#define IDB_DICE5                       185
#define IDB_DICE6                       186
#define IDD_DIALOG_HOWTOPLAY            192
#define IDC_CHECK_WHITE_ON_TOP          1000
#define IDC_BUTTON_WHITE_COLOR          1001
#define IDC_BUTTON_BLACK_COLOR          1002
#define IDC_STATIC_WHITE                1003
#define IDC_STATIC_BLACK                1004
#define IDC_EDIT_PORT_NUMBER            1007
#define IDC_IPADDRESS                   1008
#define IDC_EDIT_MESSAGE                1009
#define IDC_EDIT_RECEIVE_MESSAGE        1010
#define IDC_EDIT_HISTORY                1011
#define IDC_STATIC_ROOT_WHITE           1013
#define IDC_STATIC_BITMAP_BLACK         1013
#define IDC_STATIC_BITMAP_KNIGHT        1014
#define IDC_STATIC_BITMAP_BLACK_KING    1014
#define IDC_STATIC_BISHOP_WHITE         1015
#define IDC_STATIC_QUEEN_WHITE          1016
#define IDC_STATIC_KING_WHITE           1017
#define IDC_STATIC_PAWN_WHITE           1018
#define IDC_STATIC_ROOT_BLACK           1019
#define IDC_STATIC_BITMAP_WHITE         1019
#define IDC_STATIC_KNIGHT_BLACK         1020
#define IDC_STATIC_BITMAP_WHITE_KING    1020
#define IDC_STATIC_BISHOP_BLACK         1021
#define IDC_STATIC_QUEEN_BLACK          1022
#define IDC_STATIC_KING_BLACK           1023
#define IDC_STATIC_PAWN_BLACK           1024
#define IDC_STATIC_STATUS               1025
#define IDC_STATIC_IP_ADDRESS           1026
#define IDC_STATIC_CLIENT_STATUS        1026
#define IDC_STATIC_EMPTY                1027
#define IDC_STATIC_PIECE_TYPE1          1028
#define IDC_STATIC_PIECE_TYPE2          1029
#define IDC_STATIC_PIECE_TYPE3          1030
#define IDC_BUTTON_WHITE_PIECE_COLOR    1034
#define IDC_BUTTON_BLACK_PIECE_COLOR    1035
#define IDC_STATIC_WHITE_PIECE_COLOR    1038
#define IDC_STATIC_BLACK_PIECE_COLOR    1042
#define IDC_RADIO_AMERICAN              1044
#define IDC_RADIO_SPARSE                1045
#define IDC_NAME                        1045
#define IDC_RADIO_CROWDED               1046
#define IDC_EDIT_STRING                 1046
#define IDC_RADIO_CHINESE8x8            1047
#define IDC_RADIO_CHINESE10x10          1048
#define IDC_RADIO_INTERNATIONAL         1049
#define IDC_RADIO_ITALIAN               1050
#define IDC_RADIO_POLISH                1051
#define IDC_RADIO_RUSSIAN               1052
#define ID_VIEW_HIDE                    32771
#define ID_EDIT_OPTIONS                 32772
#define ID_TOOLS_CLIENT                 32773
#define ID_TOOLS_SERVER                 32774
#define ID_TOOLS_SENDMESSAGE            32775
#define ID_TOOLS_HISTORY                32778
#define ID_VIEW_NUMBER                  32779
#define ID_VIEW_LETTER                  32780
#define ID_FILE_SAVEHISTORY             32781
#define ID_TOOLS_PLAYHISTORY            32782
#define ID_SHELL_CLOSE                  32783
#define ID_SHELL_VIEW                   32784
#define ID_VIEW_HISTORY                 32786
#define ID_TOOLS_WHITEONTOP             32787
#define ID_EDIT_MOVEFIRST               32792
#define ID_EDIT_MOVELAST                32793
#define ID_HELP_HOWTOPLAY               32799
#define ID_TOOLS_DISCONNECT             32800
#define ID_EDIT_PROPERTIES              32801
#define D_EDIT_PROPERTIES               32802
#define ID_TOOLS_GAMETYPE               32803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
